// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2oo92BFWghvlwMof_IC1ThpBURbyo6Jg',
    appId: '1:301829087763:web:e05d665aa71f9b83aa15e6',
    messagingSenderId: '301829087763',
    projectId: 'campuslogin-c8129',
    authDomain: 'campuslogin-c8129.firebaseapp.com',
    storageBucket: 'campuslogin-c8129.appspot.com',
    measurementId: 'G-ZLR4KTYGV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK1knF5gpaiAmABrpPcAHegAnya-O3KYg',
    appId: '1:301829087763:android:e9c98d6309db0b3baa15e6',
    messagingSenderId: '301829087763',
    projectId: 'campuslogin-c8129',
    storageBucket: 'campuslogin-c8129.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY_NdWhzvA0xNm1vacRVwC7wyLodfhJTw',
    appId: '1:301829087763:ios:e11a852bfa20bb89aa15e6',
    messagingSenderId: '301829087763',
    projectId: 'campuslogin-c8129',
    storageBucket: 'campuslogin-c8129.appspot.com',
    iosClientId: '301829087763-kbrgn68f2tvk3155g036cl5jq86rrrho.apps.googleusercontent.com',
    iosBundleId: 'com.example.exfirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY_NdWhzvA0xNm1vacRVwC7wyLodfhJTw',
    appId: '1:301829087763:ios:e11a852bfa20bb89aa15e6',
    messagingSenderId: '301829087763',
    projectId: 'campuslogin-c8129',
    storageBucket: 'campuslogin-c8129.appspot.com',
    iosClientId: '301829087763-kbrgn68f2tvk3155g036cl5jq86rrrho.apps.googleusercontent.com',
    iosBundleId: 'com.example.exfirst',
  );
}
